### ISSUE TITLE
Consider representing data patterns in unicode braille

### ISSUE THREAD

**Issue by jooyoungseo** [julianna-langston/chart2music#43]
this technique has been already demonstrated in other solutions, such as [accessible graphs](https://github.com/hasadna/accessible-graphs) as well as [brailleChart](https://github.com/travisroth/brailleChart).

- [ ] Line chart, candle plot, bar plot and histogram can use line-type braille pattern like ⣀⡠⠤⠔⠒⠊⠉

- [ ] Boxplot: We may be able to represent boxplot pattern in braille unicode like this. I created this randomly, but this can show you my ideas (this has three outliers): ⠒⠒⠒⠿⠇⠿⠿⠒⠒⠒⠒ ⠠⠈⠠

- [ ] Heat map braille pattern: we could  display different dot patterns to represent different colors row by row just like below:⠿⠿⠿⠿⠿⠿⠿⠀⠇⠇⠇⠇⠇⠇⠇⠀⠣⠣⠣⠣⠣⠣⠣⠀⠭⠭⠭⠭⠭⠭⠭

**Comment by julianna-ciq** [comment]
I don't know how to assess this. @spmealin , what are your thoughts?

**Comment by spmealin** [comment]
This feature is potentially interesting. Unfortunately, since the development team does not have access to braille displays, and this requires a larger scoping effort to branch out into tactile charts, it is something that we cannot implement at the current time. I am closing this issue for now, but we can revisit it later on after we address some higher priority items.
